
* How To Use
- Download the release zip here: (soon)
- Extract to the koreader plugin folder, such as a jpdb.koplugin folder should coexist along other folders like japanese.koplugin
- Edit config.lua, filling the fields
    - You can get the deck id by clicking the deck you want in jpdb, and getting it from the url.
      For "https://jpdb.io/deck?id=85", input 85
    - The api key can be found at [[https://jpdb.io/settings][the bottom of the settings page]]
    - The sid is a little trickier to get.
      Head over to jpdb, open the developer console (F12 on Firefox, Ctrl-i on chrome), open the storage tab, click on cookies, jpdb.io and copy the "sid" value.
- Enable the plugin in koreader

* Ramdam of ideas/Todos:
- Support continuous mode too because I think it might not be able to work easy
  https://github.com/koreader/koreader/blob/f7d633cc3d0efd273a875132ac2de4fb4754dd02/frontend/apps/reader/modules/readerhighlight.lua#L738 good reference for going on posiition, screen size etc
- Toggle/Detoggle button (only on the drawing part?)
  - Also gesture
- Let user select how to style each type of word
- Log words in offline mode to mine later when online
- if api ever allows it, dump dictionary definition in custom definition
- accound for the word being never forget/blacklisted already
- check how the review stuff works for locked/redundant words
- if mash getnextvisiblechar not work, back to xml parsing
  https://github.com/Phrogz/SLAXML
  http://lua-users.org/wiki/LuaXml

* License
GPL3.0, like the rest of koreader.
A special thank you to [[https://www.cyphar.com/][cyphar]] for the deinflector code.
Thanks to [[https://github.com/msva/lua-htmlparser][msva]] for htmlparser
