name: compile_release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>1.20.1'
      - uses: https://gitea.com/actions/checkout@v3
      - name: apt update
        run:
          apt update
      - name: setup luajit
        uses: https://github.com/leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - name: download fennel
        run:
          curl -o fennel https://fennel-lang.org/downloads/fennel-1.3.0
      - name: make fennel executable
        run:
          chmod +x fennel
      - name: compile
        run:
          for file in *.fnl; do ./fennel --compile $file > $(basename $file .fnl).lua; done
      - name: install zip
        run:
          apt install zip
      - name: zip up
        run:
          zip jpdb.koplugin.zip *.lua yomichan-deinflect.json htmlparser
      - name: release gitea
        id: use-go-action
        uses: https://gitea.com/chmanie/release-action@main
        with:
          files: |-
            *
          api_key: '${{secrets.RELEASE_TOKEN}}'
